import type { Profile } from '@/types/auth';

export type ProfileField = keyof Profile;

export const NON_WRITABLE_PROFILE_FIELDS: ReadonlySet<string> = new Set([
  'id',
  'role',
  'created_at',
  'updated_at',
  'subscription_status',
  'email',
]);

export const CLIENT_WRITABLE_PROFILE_FIELDS: readonly ProfileField[] = [
  'first_name',
  'last_name',
  'bio',
  'profile_photo_url',
  'city',
  'phone',
  'website',
  'location',
  'nickname',
  'job_title',
  'profession',
  'job_type',
  'work_style',
  'skills',
  'interests',
  'portfolio_url',
  'linkedin_url',
  'twitter_url',
  'instagram_url',
  'facebook_url',
  'youtube_url',
  'github_url',
  'collaboration_availability',
  'collaboration_types',
  'preferred_work_mode',
  'collaboration_description',
  'networking_enabled',
  'onboarding_completed',
];

export const NULLABLE_STRING_PROFILE_FIELDS: ReadonlySet<ProfileField> = new Set([
  'bio',
  'profile_photo_url',
  'city',
  'phone',
  'website',
  'location',
  'nickname',
  'job_title',
  'profession',
  'job_type',
  'work_style',
  'skills',
  'interests',
  'portfolio_url',
  'linkedin_url',
  'twitter_url',
  'instagram_url',
  'facebook_url',
  'youtube_url',
  'github_url',
  'collaboration_availability',
  'preferred_work_mode',
  'collaboration_description',
]);
