name: QA Validation Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests with Coverage
        run: npm test -- --coverage

      - name: Run Console Cleanup Scanner
        run: npm run console-cleanup -- --fail-on-production

      - name: Show Replacement Suggestions
        run: npm run console-cleanup:fix -- --dry-run

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
